package edu.pitt.cs;

import com.pholser.junit.quickcheck.Property;
import com.pholser.junit.quickcheck.generator.*;
import com.pholser.junit.quickcheck.runner.JUnitQuickcheck;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;
import static org.junit.Assume.*;
import static org.hamcrest.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;

@RunWith(JUnitQuickcheck.class)
public class QuickCheckTest {

	/**
	 * <pre>
	 * Preconditions: x is an int, where x >= -10 and x <= 10.
	 * Execution steps: Call IntegerOps.square(x).
	 * Invariants: IntegerOps.square(x) returns a nonnegative integer.
	 * </pre>
	 * 
	 * @param x int generated by QuickCheck
	 */
	
	// TODO: Write @Property testSquare using invariants of your own.
	@Property
	public void testSquare(@InRange(minInt = -10, maxInt = 10) int x){
		int ret = IntegerOps.square(x);
		assertThat(ret, is(greaterThanOrEqualTo(0)));
	}
	
	/**
	 * <pre>
	 * Preconditions: x is an int, where x >= -10, x <= 10, y >= -10, and y <= 10.
	 * Execution steps: Call IntegerOps.add(x, y).
	 * Invariants: IntegerOps.add(x, y) must return an integer in between -20 and 20.
	 * </pre>
	 * 
	 * @param x int generated by QuickCheck
	 * @param y int generated by QuickCheck
	 */
	
	// TODO: Write @Property testAddInRange using invariants of your own.
	@Property
	public void testAddInRange(@InRange(minInt = -10, maxInt = 10) int x, @InRange(minInt = -10, maxInt = 10) int y){
		int ret = IntegerOps.add(x, y);
		assertThat(ret, is(greaterThanOrEqualTo(-20)));
		assertThat(ret, is(lessThanOrEqualTo(20)));
	}

	/**
	 * <pre>
	 * Preconditions: x is an int, where x >= -10, x <= 10, y >= -10, y <= 10, AND x > -y.
	 * Execution steps: Call IntegerOps.add(x, y).
	 * Invariants: IntegerOps.add(x, y) returns a nonnegative integer.
	 * </pre>
	 * 
	 * @param x int generated by QuickCheck
	 * @param y int generated by QuickCheck
	 */
	
	// TODO: Write @Property testAddGreaterThan and see if you can find additional invariants with the addition x > -y precondition.
	// Use the assumeThat API to enforce the x > -y precondition.
	@Property
	public void testAddGreaterThan(@InRange(minInt = -10, maxInt = 10) int x, @InRange(minInt = -10, maxInt = 10) int y){
		assumeThat(x, greaterThan(-y));
		int ret = IntegerOps.add(x, y);
		assertThat(ret, is(greaterThanOrEqualTo(0)));
		assertThat(ret, is(lessThanOrEqualTo(20)));
		assertThat(ret, is(equalTo(x+y)));
	}
}